<?php

namespace App\Filament\Teacher\Resources\HistoricalTimelineMazeResultResource\Pages;

use App\Filament\Teacher\Resources\HistoricalTimelineMazeResultResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListHistoricalTimelineMazeResults extends ListRecords
{
    protected static string $resource = HistoricalTimelineMazeResultResource::class;

    protected function getHeaderActions(): array
    {
        return [
            // No create action needed as results are generated by students
        ];
    }
}
