<?php

namespace App\Filament\Teacher\Resources\EquationDropResultResource\Pages;

use App\Filament\Teacher\Resources\EquationDropResultResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListEquationDropResults extends ListRecords
{
    protected static string $resource = EquationDropResultResource::class;

    protected function getHeaderActions(): array
    {
        return [
            // No create action needed as results are generated by students
        ];
    }
}
