<?php

namespace App\Filament\Teacher\Resources\TypingTestResultResource\Pages;

use App\Filament\Teacher\Resources\TypingTestResultResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListTypingTestResults extends ListRecords
{
    protected static string $resource = TypingTestResultResource::class;

    protected function getHeaderActions(): array
    {
        return [
            // No create action needed as results are generated by students
        ];
    }
}
